# Generated by Django 5.2.7 on 2025-10-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('BIDON_COMPLETO', 'Bidón completo'), ('RECARGA', 'Recarga'), ('BOTELLA', 'Botella'), ('DISPENSADOR', 'Dispensador')], max_length=20)),
                ('volumen', models.CharField(choices=[('20L', '20 litros'), ('10L', '10 litros'), ('1600CC', '1.600 cc'), ('1100CC', '1.100 cc'), ('600CC', '600 cc'), ('N/A', 'No aplica')], default='N/A', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.PositiveIntegerField(verbose_name='Precio (CLP)')),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'volumen', 'nombre'],
            },
        ),
    ]
