# Generated by Django 5.2.5 on 2025-11-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repartidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionRepartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('pedido_id', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notificación de Repartidor',
                'verbose_name_plural': 'Notificaciones de Repartidores',
                'ordering': ['-created_at'],
            },
        ),
    ]
