# Generated by Django 5.2.7 on 2025-10-30 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('nombre_completo', models.CharField(blank=True, max_length=60, verbose_name='Nombre Completo')),
                ('correo_electronico', models.EmailField(max_length=50, verbose_name='Correo Electrónico')),
                ('cargo', models.CharField(choices=[('0', 'Administrador'), ('1', 'Repartidor'), ('2', 'Operario de Planta'), ('3', 'Otro')], max_length=1, verbose_name='Cargo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('contrasena', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sucursales.sucursal')),
            ],
        ),
    ]
